apiVersion: v1
kind: Service
metadata:
  name:  {{ .Chart.Name }}
  namespace: "{{.Values.namespace}}"
  labels:
    appmon: service-yes
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Values.network.portName }}
      port: 80
      targetPort: {{.Values.network.targetPort}}